"""Constants for the BOM integration."""
ATTRIBUTION = "Data provided by the Australian Bureau of Meteorology"
COLLECTOR = "collector"
CONF_FORECASTS_BASENAME = "forecasts_basename"
CONF_FORECASTS_CREATE = "forecasts_create"
CONF_FORECASTS_DAYS = "forecasts_days"
CONF_FORECASTS_MONITORED = "forecasts_monitored"
CONF_OBSERVATIONS_BASENAME = "observations_basename"
CONF_OBSERVATIONS_CREATE = "observations_create"
CONF_OBSERVATIONS_MONITORED = "observations_monitored"
COORDINATOR = "coordinator"
DOMAIN = "bureau_of_meteorology"
